logging:
  level:
    ROOT: INFO

spring:
  main.allow-bean-definition-overriding: true
  application:
    name: social-network
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT:3306}/sone?autoreconnect=true
    username: ${DB_USER:root}
    password: ${DB_PASS:mysql}
  flyway:
    enabled: false
    url: jdbc:mysql://localhost:${DB_PORT:3306}/sone
    schemas: sone
    user: ${DB_USER:root}
    password: ${DB_PASS:mysql}