logging:
  level:
    ROOT: INFO

spring:
  main.allow-bean-definition-overriding: true
  application:
    name: social-network
  datasource:
    url: jdbc:${DB_URL:mysql://localhost:3306/sone?autoreconnect=true}
    username: ${DB_USER:root}
    password: ${DB_PASS:mysql}
  flyway:
    url: jdbc:${DB_URL:mysql://localhost:3306/sone}
    user: ${DB_USER:root}
    password: ${DB_PASS:mysql}