spring:
  main.allow-bean-definition-overriding: true
  application:
    name: social-media
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT:3306}/socme
    username: ${DB_USER:root}
    password: ${DB_PASS:mysql}
  flyway:
    placeholders:
      dbuser: ${spring.datasource.username}
    #    enabled: false
    url: jdbc:mysql://localhost:${DB_PORT:3306}/socme
    schemas: public
    user: ${DB_USER:root}
    password: ${DB_PASS:mysql}